import Config

truthy? = fn
  nil, default -> default
  value, _default -> String.downcase(value) in ["1", "true", "yes", "on"]
end

enable_code_reloader = truthy?.(System.get_env("PHX_CODE_RELOADER"), true)
enable_debug_errors = truthy?.(System.get_env("PHX_DEBUG_ERRORS"), enable_code_reloader)
enable_live_reload = truthy?.(System.get_env("PHX_LIVE_RELOAD"), enable_code_reloader)
enable_dev_routes = truthy?.(System.get_env("PHX_DEV_ROUTES"), true)
enable_expensive_runtime_checks = truthy?.(System.get_env("PHX_EXPENSIVE_RUNTIME_CHECKS"), true)

# Configure your database
config :poker_backend, PokerBackend.Repo,
  username: "postgres",
  password: "postgres",
  hostname: System.get_env("DB_HOSTNAME") || "localhost",
  database: "poker_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :poker_backend, PokerBackendWeb.Endpoint,
  # Bind to 0.0.0.0 to expose the server to the docker host machine.
  # This makes make the service accessible from any network interface.
  # Change to `ip: {127, 0, 0, 1}` to allow access only from the server machine.
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  code_reloader: enable_code_reloader,
  debug_errors: enable_debug_errors,
  secret_key_base: "/i/E4TDnoiyk96jZUd089LS15RkMinsJ2Hbso496OD9PoXYS8ESXriBdkMQX3hsO",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

if enable_live_reload do
  config :poker_backend, PokerBackendWeb.Endpoint,
    live_reload: [
      web_console_logger: true,
      patterns: [
        # Static assets, except user uploads
        ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
        # Gettext translations
        ~r"priv/gettext/.*\.po$"E,
        # Router, Controllers, LiveViews and LiveComponents
        ~r"lib/poker_backend_web/router\.ex$"E,
        ~r"lib/poker_backend_web/(controllers|live|components)/.*\.(ex|heex)$"E
      ]
    ]
end

# Enable dev routes for dashboard and mailbox
config :poker_backend, dev_routes: enable_dev_routes

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: enable_expensive_runtime_checks
