FROM golang:1.23-alpine AS build

WORKDIR /app
COPY . .
RUN cd backend && go build -o /server cmd/server/main.go

FROM alpine:3.18
WORKDIR /
COPY --from=build /server /server
COPY backend/data /data
EXPOSE 4000
CMD ["/server"]
